/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '../../app/app-routing.module';
import * as import9 from '@angular/http/src/http_module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/common/src/location/location';
import * as import24 from '@angular/router/src/url_tree';
import * as import25 from '@angular/router/src/router_outlet_map';
import * as import26 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import27 from '@angular/router/src/router_preloader';
import * as import28 from '@angular/http/src/backends/browser_xhr';
import * as import29 from '@angular/http/src/base_response_options';
import * as import30 from '@angular/http/src/backends/xhr_backend';
import * as import31 from '@angular/http/src/base_request_options';
import * as import32 from '../../app/services/catalog.service';
import * as import33 from '@angular/core/src/di/injector';
import * as import34 from './components/catalog/catalog.component.ngfactory';
import * as import35 from './components/app/app.component.ngfactory';
import * as import36 from '@angular/core/src/application_tokens';
import * as import37 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import38 from '@angular/platform-browser/src/dom/events/key_events';
import * as import39 from '@angular/core/src/zone/ng_zone';
import * as import40 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import41 from '@angular/common/src/location/platform_location';
import * as import42 from '@angular/common/src/location/location_strategy';
import * as import43 from '../../app/components/catalog/catalog.component';
import * as import44 from '@angular/router/src/url_handling_strategy';
import * as import45 from '@angular/router/src/router';
import * as import46 from '@angular/core/src/console';
import * as import47 from '@angular/core/src/i18n/tokens';
import * as import48 from '@angular/core/src/error_handler';
import * as import49 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import50 from '@angular/platform-browser/src/dom/animation_driver';
import * as import51 from '@angular/core/src/render/api';
import * as import52 from '@angular/core/src/security';
import * as import53 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import54 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import55 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import56 from '@angular/router/src/router_config_loader';
import * as import57 from '@angular/router/src/router_state';
import * as import58 from '@angular/http/src/interfaces';
import * as import59 from '@angular/http/src/http';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _ROUTER_FORROOT_GUARD_5:any;
  _RouterModule_6:import7.RouterModule;
  _AppRoutingModule_7:import8.AppRoutingModule;
  _HttpModule_8:import9.HttpModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import11.ApplicationInitStatus;
  _Testability_14:import12.Testability;
  _ApplicationRef__15:import13.ApplicationRef_;
  __ApplicationRef_16:any;
  __Compiler_17:import14.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import16.EventManager;
  __DomSharedStylesHost_23:import17.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import18.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import19.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import20.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import21.Title;
  __RadioControlRegistry_34:import22.RadioControlRegistry;
  __ROUTER_CONFIGURATION_35:any;
  __LocationStrategy_36:any;
  __Location_37:import23.Location;
  __UrlSerializer_38:import24.DefaultUrlSerializer;
  __RouterOutletMap_39:import25.RouterOutletMap;
  __NgModuleFactoryLoader_40:import26.SystemJsNgModuleLoader;
  __ROUTES_41:any[];
  __Router_42:any;
  __ActivatedRoute_43:any;
  _NoPreloading_44:import27.NoPreloading;
  _PreloadingStrategy_45:any;
  _RouterPreloader_46:import27.RouterPreloader;
  __PreloadAllModules_47:import27.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_48:any[];
  __BrowserXhr_49:import28.BrowserXhr;
  __ResponseOptions_50:import29.BaseResponseOptions;
  __XSRFStrategy_51:any;
  __XHRBackend_52:import30.XHRBackend;
  __RequestOptions_53:import31.BaseRequestOptions;
  __Http_54:any;
  __CatalogService_55:import32.CatalogService;
  constructor(parent:import33.Injector) {
    super(parent,[
      import34.CatalogComponentNgFactory,
      import34.WantedComponentNgFactory,
      import34.MyComponentNgFactory,
      import34.CatalogComponentNgFactory,
      import34.CatalogComponentNgFactory,
      import35.AppComponentNgFactory
    ]
    ,[import35.AppComponentNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_16():any {
    if ((this.__ApplicationRef_16 == (null as any))) { (this.__ApplicationRef_16 = this._ApplicationRef__15); }
    return this.__ApplicationRef_16;
  }
  get _Compiler_17():import14.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import14.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import36._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import37.DomEventsPlugin(),
      new import38.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import16.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import39.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import17.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import18.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import40._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import40.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import20.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import20.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import21.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import21.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == (null as any))) { (this.__RadioControlRegistry_34 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _ROUTER_CONFIGURATION_35():any {
    if ((this.__ROUTER_CONFIGURATION_35 == (null as any))) { (this.__ROUTER_CONFIGURATION_35 = {}); }
    return this.__ROUTER_CONFIGURATION_35;
  }
  get _LocationStrategy_36():any {
    if ((this.__LocationStrategy_36 == (null as any))) { (this.__LocationStrategy_36 = import7.provideLocationStrategy(this.parent.get(import41.PlatformLocation),this.parent.get(import42.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_35)); }
    return this.__LocationStrategy_36;
  }
  get _Location_37():import23.Location {
    if ((this.__Location_37 == (null as any))) { (this.__Location_37 = new import23.Location(this._LocationStrategy_36)); }
    return this.__Location_37;
  }
  get _UrlSerializer_38():import24.DefaultUrlSerializer {
    if ((this.__UrlSerializer_38 == (null as any))) { (this.__UrlSerializer_38 = new import24.DefaultUrlSerializer()); }
    return this.__UrlSerializer_38;
  }
  get _RouterOutletMap_39():import25.RouterOutletMap {
    if ((this.__RouterOutletMap_39 == (null as any))) { (this.__RouterOutletMap_39 = new import25.RouterOutletMap()); }
    return this.__RouterOutletMap_39;
  }
  get _NgModuleFactoryLoader_40():import26.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_40 == (null as any))) { (this.__NgModuleFactoryLoader_40 = new import26.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import26.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_40;
  }
  get _ROUTES_41():any[] {
      if ((this.__ROUTES_41 == (null as any))) { (this.__ROUTES_41 = [[
        {
          path: 'catalog',
          component: import43.CatalogComponent
        }
        ,
        {
          path: 'wanted',
          component: import43.WantedComponent
        }
        ,
        {
          path: 'my',
          component: import43.MyComponent
        }
        ,
        {
          path: '',
          component: import43.CatalogComponent
        }
        ,
        {
          path: '**',
          component: import43.CatalogComponent
        }

      ]
    ]); }
    return this.__ROUTES_41;
  }
  get _Router_42():any {
    if ((this.__Router_42 == (null as any))) { (this.__Router_42 = import7.setupRouter(this._ApplicationRef_16,this._UrlSerializer_38,this._RouterOutletMap_39,this._Location_37,this,this._NgModuleFactoryLoader_40,this._Compiler_17,this._ROUTES_41,this._ROUTER_CONFIGURATION_35,this.parent.get(import44.UrlHandlingStrategy,(null as any)))); }
    return this.__Router_42;
  }
  get _ActivatedRoute_43():any {
    if ((this.__ActivatedRoute_43 == (null as any))) { (this.__ActivatedRoute_43 = import7.rootRoute(this._Router_42)); }
    return this.__ActivatedRoute_43;
  }
  get _PreloadAllModules_47():import27.PreloadAllModules {
    if ((this.__PreloadAllModules_47 == (null as any))) { (this.__PreloadAllModules_47 = new import27.PreloadAllModules()); }
    return this.__PreloadAllModules_47;
  }
  get _APP_BOOTSTRAP_LISTENER_48():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_48 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_48 = [import7.initialRouterNavigation(this._Router_42,this._ApplicationRef_16,this._RouterPreloader_46,this._ROUTER_CONFIGURATION_35)]); }
    return this.__APP_BOOTSTRAP_LISTENER_48;
  }
  get _BrowserXhr_49():import28.BrowserXhr {
    if ((this.__BrowserXhr_49 == (null as any))) { (this.__BrowserXhr_49 = new import28.BrowserXhr()); }
    return this.__BrowserXhr_49;
  }
  get _ResponseOptions_50():import29.BaseResponseOptions {
    if ((this.__ResponseOptions_50 == (null as any))) { (this.__ResponseOptions_50 = new import29.BaseResponseOptions()); }
    return this.__ResponseOptions_50;
  }
  get _XSRFStrategy_51():any {
    if ((this.__XSRFStrategy_51 == (null as any))) { (this.__XSRFStrategy_51 = import9._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_51;
  }
  get _XHRBackend_52():import30.XHRBackend {
    if ((this.__XHRBackend_52 == (null as any))) { (this.__XHRBackend_52 = new import30.XHRBackend(this._BrowserXhr_49,this._ResponseOptions_50,this._XSRFStrategy_51)); }
    return this.__XHRBackend_52;
  }
  get _RequestOptions_53():import31.BaseRequestOptions {
    if ((this.__RequestOptions_53 == (null as any))) { (this.__RequestOptions_53 = new import31.BaseRequestOptions()); }
    return this.__RequestOptions_53;
  }
  get _Http_54():any {
    if ((this.__Http_54 == (null as any))) { (this.__Http_54 = import9.httpFactory(this._XHRBackend_52,this._RequestOptions_53)); }
    return this.__Http_54;
  }
  get _CatalogService_55():import32.CatalogService {
    if ((this.__CatalogService_55 == (null as any))) { (this.__CatalogService_55 = new import32.CatalogService(this._Http_54)); }
    return this.__CatalogService_55;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._ROUTER_FORROOT_GUARD_5 = import7.provideForRootGuard(this.parent.get(import45.Router,(null as any)));
    this._RouterModule_6 = new import7.RouterModule(this._ROUTER_FORROOT_GUARD_5);
    this._AppRoutingModule_7 = new import8.AppRoutingModule();
    this._HttpModule_8 = new import9.HttpModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import12.Testability(this.parent.get(import39.NgZone));
    this._ApplicationRef__15 = new import13.ApplicationRef_(this.parent.get(import39.NgZone),this.parent.get(import46.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_14);
    this._NoPreloading_44 = new import27.NoPreloading();
    this._PreloadingStrategy_45 = this._NoPreloading_44;
    this._RouterPreloader_46 = new import27.RouterPreloader(this._Router_42,this._NgModuleFactoryLoader_40,this._Compiler_17,this,this._PreloadingStrategy_45);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_5; }
    if ((token === import7.RouterModule)) { return this._RouterModule_6; }
    if ((token === import8.AppRoutingModule)) { return this._AppRoutingModule_7; }
    if ((token === import9.HttpModule)) { return this._HttpModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import47.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import48.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import12.Testability)) { return this._Testability_14; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import14.Compiler)) { return this._Compiler_17; }
    if ((token === import36.APP_ID)) { return this._APP_ID_18; }
    if ((token === import49.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import16.EventManager)) { return this._EventManager_22; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import50.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import51.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import52.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import53.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import54.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import21.Title)) { return this._Title_33; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import7.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_35; }
    if ((token === import42.LocationStrategy)) { return this._LocationStrategy_36; }
    if ((token === import23.Location)) { return this._Location_37; }
    if ((token === import24.UrlSerializer)) { return this._UrlSerializer_38; }
    if ((token === import25.RouterOutletMap)) { return this._RouterOutletMap_39; }
    if ((token === import55.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_40; }
    if ((token === import56.ROUTES)) { return this._ROUTES_41; }
    if ((token === import45.Router)) { return this._Router_42; }
    if ((token === import57.ActivatedRoute)) { return this._ActivatedRoute_43; }
    if ((token === import27.NoPreloading)) { return this._NoPreloading_44; }
    if ((token === import27.PreloadingStrategy)) { return this._PreloadingStrategy_45; }
    if ((token === import27.RouterPreloader)) { return this._RouterPreloader_46; }
    if ((token === import27.PreloadAllModules)) { return this._PreloadAllModules_47; }
    if ((token === import36.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_48; }
    if ((token === import28.BrowserXhr)) { return this._BrowserXhr_49; }
    if ((token === import29.ResponseOptions)) { return this._ResponseOptions_50; }
    if ((token === import58.XSRFStrategy)) { return this._XSRFStrategy_51; }
    if ((token === import30.XHRBackend)) { return this._XHRBackend_52; }
    if ((token === import31.RequestOptions)) { return this._RequestOptions_53; }
    if ((token === import59.Http)) { return this._Http_54; }
    if ((token === import32.CatalogService)) { return this._CatalogService_55; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
    this._RouterPreloader_46.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);