/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/my.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../app/catalog.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/core/src/security';
export class Wrapper_MyComponent {
  /*private*/ _eventHandler:Function;
  context:import0.MyComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any) {
    this._changed = false;
    this.context = new import0.MyComponent(p0,p1);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_MyComponent_Host:import2.RenderComponentType = (null as any);
class _View_MyComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  compView_0:import1.AppView<import0.MyComponent>;
  _MyComponent_0_4:Wrapper_MyComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyComponent_Host0,renderType_MyComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'my',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    this.compView_0 = viewFactory_MyComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyComponent_0_4 = new Wrapper_MyComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.CatalogService));
    this._appEl_0.initComponent(this._MyComponent_0_4.context,this.compView_0);
    this.compView_0.create(this._MyComponent_0_4.context,(null as any));
    this.init(this._el_0,[this._el_0],(null as any));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyComponent) && (0 === requestNodeIndex))) { return this._MyComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyComponent_0_4.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.detectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
function viewFactory_MyComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MyComponent_Host === (null as any))) { (renderType_MyComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MyComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyComponentNgFactory:import11.ComponentFactory<import0.MyComponent> = new import11.ComponentFactory<import0.MyComponent>('my',viewFactory_MyComponent_Host0,import0.MyComponent);
const styles_MyComponent:any[] = ([] as any[]);
var renderType_MyComponent:import2.RenderComponentType = (null as any);
class _View_MyComponent0 extends import1.AppView<import0.MyComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TemplateRef_25_5:any;
  _NgFor_25_6:import12.Wrapper_NgFor;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyComponent0,renderType_MyComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'[my component html]\n\n',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'My Flosses',(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,parentRenderNode,'table',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'thead',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_8,'th',new import4.InlineArray2(2,'width','200'),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'DMC Code',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_8,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Name',(null as any));
    this._text_15 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_8,'th',new import4.InlineArray2(2,'width','150'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Tile',(null as any));
    this._text_18 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_19 = import4.createRenderElement(this.renderer,this._el_8,'th',new import4.InlineArray2(2,'width','150'),(null as any));
    this._text_20 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_6,'\n  ',(null as any));
    this._text_22 = this.renderer.createText(this._el_4,'\n  ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_4,'tbody',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n    ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_23,(null as any));
    this._appEl_25 = new import3.AppElement(25,23,this,this._anchor_25);
    this._TemplateRef_25_5 = new import13.TemplateRef_(this._appEl_25,viewFactory_MyComponent1);
    this._NgFor_25_6 = new import12.Wrapper_NgFor(this._appEl_25.vcRef,this._TemplateRef_25_5,this.parentInjector.get(import14.IterableDiffers),this.ref);
    this._text_26 = this.renderer.createText(this._el_23,'\n  ',(null as any));
    this._text_27 = this.renderer.createText(this._el_4,'\n',(null as any));
    this.init((null as any),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27
    ]
    ,(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import15.NgFor) && (25 === requestNodeIndex))) { return this._NgFor_25_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_25_0_0:any = this.context.catalog;
    this._NgFor_25_6.check_ngForOf(currVal_25_0_0,throwOnChange,false);
    this._NgFor_25_6.ngDoCheck(this,this._anchor_25,throwOnChange);
    this._appEl_25.detectChangesInNestedViews(throwOnChange);
  }
  destroyInternal():void {
    this._appEl_25.destroyNestedViews();
  }
}
export function viewFactory_MyComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MyComponent> {
  if ((renderType_MyComponent === (null as any))) { (renderType_MyComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_MyComponent,{})); }
  return new _View_MyComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_MyComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyComponent1,renderType_MyComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_8,'span',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_12,'a',new import4.InlineArray2(2,'class','alert button add-button'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'Delete',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = import4.subscribeToRenderElement(this,this._el_13,new import4.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_13));
    this.init(this._el_0,[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15
    ]
    ,[disposable_0]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_16:any = import4.interpolate(1,'',this.context.$implicit.dmc,'');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_3,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_6,currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = ('#' + this.context.$implicit.rgb);
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementStyle(this._el_9,'background-color',((this.viewUtils.sanitizer.sanitize(import16.SecurityContext.STYLE,currVal_18) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import16.SecurityContext.STYLE,currVal_18).toString()));
      this._expr_18 = currVal_18;
    }
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
  handleEvent_13(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.parent.context.deleteFloss(this.context.$implicit,'my',$event)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}
function viewFactory_MyComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyComponent1(viewUtils,parentInjector,declarationEl);
}